(jde-project-file-version "1.0")
(jde-set-variables
 '(jde-ant-enable-find t)
 '(jde-ant-read-target t)
 '(jde-electric-return-p t)
 '(jde-bug-jpda-directory "")
 '(jde-enable-abbrev-mode t)
 '(jde-global-classpath (quote ("./lib" "./build/classes" "./src")))
 '(jde-jdk-doc-url "/opt/android-sdk/docs/reference/index.html")
 '(jde-compile-option-directory "./build/classes")
 '(jde-complete-function (quote jde-complete-menu))
 '(jde-sourcepath (quote ("./src")))
 '(jde-run-application-class "mozg.gui.ExcelToAnkiConverter")
 '(jde-complete-insert-method-signature nil)
 '(jde-help-docsets (quote (("JDK API" "http://java.sun.com/javase/6/docs/api" nil) ("JDK API" "/opt/android-sdk/docs/reference/" nil) ("JDK API" "http://help.eclipse.org/helios/topic/org.eclipse.platform.doc.isv/reference/api/" nil)))))
